Feat: Check test fail

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -15,3 +15,8 @@ jobs:
       run: make test -j
     - name: run test
       run: ./ircserv_test
+    - name: Check Status
+      if: ${{ failure }}
+      run: |
+        echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+        exit 1
